export const GET_RECIPES = 'GET_RECIPES';
export const GET_RECIPES_BY_AUTHOR = 'GET_RECIPES_BY_AUTHOR';
export const GET_RECIPES_BY_ID = 'GET_RECIPES_BY_ID';
export const SELECT_RECIPE = 'SELECT_RECIPE';